
name: armhf-rpi-lean-image-build

concurrency:
  group: armhf-rpi-lean-image-build-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "build_sdcard.sh"
      - "ci/armhf-rpi/**"
  pull_request:
    branches: ["main"]
    paths:
      - "build_sdcard.sh"
      - "ci/armhf-rpi/**"

jobs:
  armhf-rpi-image-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set values
        id: set_values
        run: |
          echo "BUILD_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
          echo "BUILD_VERSION=$(git describe --always --tags)" >> $GITHUB_ENV
          if [ -z "$GITHUB_HEAD_REF" ]; then
            echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          fi
          if [[ "${{github.event_name}}" == "pull_request" ]]; then
            echo "::set-output name=github_user::${{github.event.pull_request.head.repo.owner.login}}"
          else
            echo "::set-output name=github_user::$(echo ${{github.repository}} | cut -d'/' -f1)"
          fi

      - name: Display the build name
        run: echo "Building the btcticker-armhf-rpi-lean-image-${{ env.BUILD_DATE }}-${{ env.BUILD_VERSION }}"

      - name: Run the build script
        run: |
          echo "Using the variables: --pack lean --github_user ${{steps.set_values.outputs.github_user}} --branch ${{env.BRANCH_NAME}}"
          cd ci/armhf-rpi
          bash packer.build.armhf-rpi.sh --pack lean --github_user ${{steps.set_values.outputs.github_user}} --branch ${{env.BRANCH_NAME}}

      - name: Compute checksum of the raw image
        run: |
          cd ci/armhf-rpi
          sha256sum btcticker-armhf-rpi-lean.img > btcticker-armhf-rpi-lean.img.sha256

      - name: Compress image
        run: |
          cd ci/armhf-rpi
          gzip -v9 btcticker-armhf-rpi-lean.img

      - name: Compute checksum of the compressed image
        run: |
          cd ci/armhf-rpi
          sha256sum btcticker-armhf-rpi-lean.img.gz > btcticker-armhf-rpi-lean.img.gz.sha256

      - name: Upload the image and checksums
        uses: actions/upload-artifact@v3
        with:
          name: btcticker-armhf-rpi-image-${{ env.BUILD_DATE }}-${{ env.BUILD_VERSION }}
          path: |
            ${{ github.workspace }}/ci/armhf-rpi/btcticker-armhf-rpi-lean.img.sha256
            ${{ github.workspace }}/ci/armhf-rpi/btcticker-armhf-rpi-lean.img.gz
            ${{ github.workspace }}/ci/armhf-rpi/btcticker-armhf-rpi-lean.img.gz.sha256
